### ISSUE TITLE
 Icons for identifying post type

### ISSUE THREAD

**Issue by enridaga** [mk-smart/mkinsight-theme#5]
Display icons for the type of posts:
- Data
- Report
- Page

**Comment by DrPollo** [comment]
Where?

**Comment by DrPollo** [comment]
Search results, page title

Icons are in template

**Comment by DrPollo** [comment]
report: pie-chart3.png
data: data-green.png
news: 
essential: 
idea: light-bulb-green.png

page: document.png (default)
